### ISSUE TITLE
Documentation/rdoc incomplete

### ISSUE THREAD

**Issue by fwolfst** [ruby/matrix#18]
The ruby-doc page (https://ruby-doc.org/stdlib-2.7.2/libdoc/matrix/rdoc/Matrix.html) does not contain all of the documentation and the README does not list a different authoritative source.
Where can I find proper rendered documentation? The code does seem to have all the necessary annotations.

**Comment by hsbt** [comment]
ruby-doc.org is not an official documentation site. I didn't know how generate it.

**Comment by marcandre** [comment]
This page should have all the methods: https://docs.ruby-lang.org/en/master/Matrix.html

**Comment by bensherman** [comment]
It looks like the docs fell off the master branch - I came here because the inverse method is missing on documentation in dash docsets, (which I believe is generated from the same place as ruby-doc.org). I am happy to dig into this to figure out what's up, but thought a maintainer (or someone better equipped for this than me) might find it super obvious.  The complete docs are in https://docs.ruby-lang.org/en/3.0.0/Matrix.html and rdoc and yard both work properly in this repo, so I am unclear on what is keeping the docs from making it into the final rendered docs.
